### ISSUE TITLE
Workspace folder does not exist with ./

### ISSUE THREAD

**Issue by dynagence** [ChiriVulpes/vscode-find-and-replace-in-selected-files#1]
Hi,
When I click "Find in Selected Files" I have this error : "Workspace folder does not exist: ...".
I have to delete "./" before the files name.
How can I modify to not add "./"before files.
Your extention is great !

**Comment by dynagence** [comment]
I replaced line 12 in FindAndReplaceInFilesCommand.js
`//return filePath[0] === "." || filePath[0] === "/" || filePath[0] === "\\" ? filePath : `./${filePath}`;`
`return filePath;`

**Comment by ChiriVulpes** [comment]
Thank you! Never tested with multi root workspaces.

**Comment by dynagence** [comment]
Your update is not ok.
Line 15 I have to delete ./
`//return './${workspacePrefix}${filePath}';`
`return '${workspacePrefix}${filePath}';`

**Comment by ChiriVulpes** [comment]
> Your update is not ok. Line 15 I have to delete ./ `//return './${workspacePrefix}${filePath}';` `return '${workspacePrefix}${filePath}';`

@dynagence Your workspace might be misconfigured, because this is working exactly as intended. Workspace roots *must* have a name that doesn't contain slashes, because the format for finding in files or folders is `./ROOT NAME/relative/path`, and therefore, if you have a slash in the name, it thinks you're trying to search in some other invalid path. See: https://github.com/microsoft/vscode/issues/61297

I didn't decide the way include/exclude paths work in VSCode, I think it's very confusing personally — why is it not `ROOT NAME:relative/path` for example, making `./` relative for all roots? Unfortunately, there's nothing I can do about that.

**Comment by dynagence** [comment]
My workspaces names doesn't contain slashes.

**Comment by ChiriVulpes** [comment]
What's it doing, then? You'll need to give me more information to figure out what's actually happening.

**Comment by dynagence** [comment]
![image](https://github.com/ChiriVulpes/vscode-find-and-replace-in-selected-files/assets/3965049/6068f246-21a1-4d94-9982-eeb8c00cfd09)
![image](https://github.com/ChiriVulpes/vscode-find-and-replace-in-selected-files/assets/3965049/2af429ae-ca13-4e08-afc9-59661b9d0f9a)

![image](https://github.com/ChiriVulpes/vscode-find-and-replace-in-selected-files/assets/3965049/f697f399-2fb1-4d11-800a-9837c88c3523)
![image](https://github.com/ChiriVulpes/vscode-find-and-replace-in-selected-files/assets/3965049/add742dd-bee4-4663-8b01-f3d30fec4a4b)

![image](https://github.com/ChiriVulpes/vscode-find-and-replace-in-selected-files/assets/3965049/3770b8f3-0104-426b-ba76-82e0536eb7b6)

**Comment by ChiriVulpes** [comment]
Can I see your workspace file? (F1, "Open Workspace Settings") And what file/folder are you right clicking on to "find in selected files"? Are you right clicking on `index.php`?

**Comment by dynagence** [comment]
Yes I right clicked "find in selected files" in index.php. It's add "./index.php". I have to remove ./

`{
	"folders": [
		{
			"path": "web-dedibox"
		}
	],
	"settings": {
		"editor.codeActionsOnSave": {
			
		}
	}
}`

**Comment by ChiriVulpes** [comment]
Hmmm... I don't really understand your workspace. Your listed roots only contain `web-dedibox`, but in your screenshot above the only root I see is `www-plesk`?

**Comment by dynagence** [comment]
Sorry it's another workspace, but it's egal...

{
	"folders": [
		{
			"path": "www-plesk"
		}
	],
	"settings": {
		"editor.codeActionsOnSave": {
			
		}
	}
}

**Comment by ChiriVulpes** [comment]
Right clicking on index.php in that workspace should fill in the "files to include" box with `./www-plesk/index.php`. Or if you have `admin/index.php` and right click on that, that should fill in the box with `./www-plesk/admin/index.php`. But it doesn't? What is it being filled in with instead?

**Comment by dynagence** [comment]
No, it fills ./index.php ou ./admin/index.php. It should fill index.php or admin/index.php.
If I fill ./www-plesk/index.php it returns that the folder does not exist.
See my screenshots or/and make tests...

**Comment by ChiriVulpes** [comment]
What happens if you right click on a folder and use the base/default VSCode command "Find in Folder"?

**Comment by dynagence** [comment]
Sorry, ./www-plesk/admin/index.php is OK !
With default "Find in Folder" it fills ./www-plesk/recrutements-photos. It's OK
You just have to add th folder "path": "www-plesk".
Thanks

**Comment by dynagence** [comment]
Were you able to fix the bug?

**Comment by ChiriVulpes** [comment]
I haven't reproduced any bug, the way it works right now should be correct

**Comment by dynagence** [comment]
The bug is still present, but I modified your code. Thanks anyway.
